# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  USE_BSPM: "true"  
  TRIM_APT_SOURCES: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          #- {os: macOS-latest}
          #- {os: ubuntu-latest}
          - name: gcc-11
            cxx: g++-11
            cc: gcc-11
          - name: gcc-12
            cxx: g++-12
            cc: gcc-12

    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          # use 'r2u' variant
          curl -OLs https://eddelbuettel.github.io/r-ci/r2u/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap
          
      - name: Compiler
        run: |
          ./run.sh install_aptget ${{ matrix.cxx }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${{ matrix.cc }} 60 --slave /usr/bin/g++ g++ /usr/bin/${{matrix.cxx }}
          g++ --version
          
      - name: Dependencies
        run: |
          ./run.sh install_aptget libgmp-dev libmpfr-dev
          ./run.sh install_deps
          ./run.sh install_r uniformly  # this should not be needed

      - name: Test
        run: ./run.sh run_tests

      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: ./run.sh coverage
